Namespace(task='assignment', test_dir='/network/scratch/z/zhaoyu.li/satbench/medium/ca/test/', checkpoint='/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/checkpoints/model_best.pt', test_splits=['sat'], test_sample_size=None, test_augment_ratio=None, label=None, decoding='standard', data_fetching='parallel', batch_size=64, seed=0, graph='vcg', init_emb='learned', model='ggnn', dim=128, n_iterations=32, n_mlp_layers=2, activation='relu', satisfiability_readout='literal', multiple_assignments=False, log_dir='/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08', log='/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/eval_task=assignment_difficulty=medium_dataset=ca_splits=sat_decoding=standard_n_iterations=32_checkpoint=model_best.txt', device=device(type='cuda'))
Loading model checkpoint from /network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/checkpoints/model_best.pt..
Traceback (most recent call last):
  File "/home/mila/z/zhaoyu.li/SATBench/eval_model.py", line 142, in <module>
    main()
  File "/home/mila/z/zhaoyu.li/SATBench/eval_model.py", line 68, in main
    checkpoint = torch.load(opts.checkpoint)
  File "/home/mila/z/zhaoyu.li/.conda/envs/satbench/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mila/z/zhaoyu.li/.conda/envs/satbench/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mila/z/zhaoyu.li/.conda/envs/satbench/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/checkpoints/model_best.pt'
Namespace(task='assignment', test_dir='/network/scratch/z/zhaoyu.li/satbench/medium/ca/test/', checkpoint='/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/checkpoints/model_best.pt', test_splits=['sat'], test_sample_size=None, test_augment_ratio=None, label=None, decoding='standard', data_fetching='parallel', batch_size=64, seed=0, graph='vcg', init_emb='learned', model='ggnn', dim=128, n_iterations=32, n_mlp_layers=2, activation='relu', satisfiability_readout='literal', multiple_assignments=False, log_dir='/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08', log='/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/eval_task=assignment_difficulty=medium_dataset=ca_splits=sat_decoding=standard_n_iterations=32_checkpoint=model_best.txt', device=device(type='cuda'))
Loading model checkpoint from /network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/checkpoints/model_best.pt..
Traceback (most recent call last):
  File "/home/mila/z/zhaoyu.li/SATBench/eval_model.py", line 142, in <module>
    main()
  File "/home/mila/z/zhaoyu.li/SATBench/eval_model.py", line 68, in main
    checkpoint = torch.load(opts.checkpoint)
  File "/home/mila/z/zhaoyu.li/.conda/envs/satbench/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mila/z/zhaoyu.li/.conda/envs/satbench/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mila/z/zhaoyu.li/.conda/envs/satbench/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/network/scratch/z/zhaoyu.li/runs/task=assignment_difficulty=medium_dataset=ca_splits=sat_label=None_loss=unsupervisedv2/graph=vcg_init_emb=learned_model=ggnn_n_iterations=32_seed=123_lr=0.0001_weight_decay=1e-08/checkpoints/model_best.pt'
